# -*- coding: utf-8 -*-
"""FAQ_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SksEW2YA9cTKj0FMKxUPpWwdJo13NTFm
"""

#  simple rule-based chatbot for FAQs
RULES = {
    ("hello", "hi"): "Hello! How can I help you today? You can ask me about our hours, location, or services.",
    ("hours", "open"): "We are open from 9:00 AM to 5:00 PM, Monday to Friday.",
    ("location", "address"): "You can find us at 123 Main Street, Anytown.",
    ("services", "what do you do"): "We offer a variety of services, including consulting, support, and sales. What are you looking for?",
    ("contact", "phone"): "You can call our support team at (555) 123-4567.",
    ("bye", "exit"): "Goodbye! Have a great day."
}

def get_faq_answer(question):
  question_lower = question.lower()
  for keywords, answer in RULES.items():
    if any(key in question_lower for key in keywords):
      return answer
  return "I'm sorry, I don't understand that question. Please try rephrasing, or ask about our hours, location, or services."

def run_chatbot():
    print("Bot: Hello! I am a simple FAQ bot.")
    print("Bot: You can ask me about our hours, location, or services.")
    print("Bot: Type 'bye' or 'exit' to quit.\n")
    while True:
        user_input = input("You: ")
        bot_answer = get_faq_answer(user_input)
        print(f"Bot: {bot_answer}\n")
        if "goodbye" in bot_answer.lower():
          break


if __name__ == "__main__":
    run_chatbot()